---
layout: blog_post
title: "Node.js Login with Express and OIDC"
author: matt-raible
by: advocate
communities: [javascript]
description: "This screencast shows you how to create an Express app and add login to it in just a few steps."
tags: [nodejs, javascript, login, oidc, authentication, logout]
tweets:
- "Add login to your @nodejs in just a few minutes!"
- "Do you love adding login to your Node.js apps? Probably not! Learn how to do it with an easy button from @mraible."
- "New to Node.js? Check out how easy it is to add a login feature with @okta!"
image: // todo
type: conversion
---

Node.js just celebrated its 11th birthday! It's pretty crazy to think it was way back in 2009 when the JavaScript Renaissance got a huge boost. In case you're not aware, the JavaScript Renaissance began in around 2004 with Ajax, increased exponentionally with jQuery in the mid-2000s with jQuery,then really took off with Node.js and a plethora of plethora of early JavaScript web frameworks, including Backbone.js, Ember.js, and AngularJS.

Today, I'd like to show you the power of Node.js with a simple login example. Express.js is one of the oldest and most-used server-side MVC frameworks for Node.js. Okta happens to provide an https://github.com/okta/okta-oidc-js/tree/master/packages/oidc-middleware#readme[OIDC Middleware package] that integrates with Express to secure your app with login and logout functionality.

To show how it all works, I created a screencast: https://youtu.be/BgpsNi_6mzg[Node.js Login with Express and OIDC].

++++
<div style="text-align: center; margin-bottom: 1.25rem">
<iframe width="700" height="394" src="https://www.youtube.com/embed/BgpsNi_6mzg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
++++

NOTE: https://github.com/oktadeveloper/schematics[OktaDev Schematics] was used in the making of this video. See its https://github.com/oktadeveloper/schematics#express[Express documentation] to reproduce the steps yourself, or follow the instructions below.

== Create an Express App and Add Login in 5 Steps

. Create a new project with https://expressjs.com/en/starter/generator.html[express-generator] and pug for the view.
+
[source,shell]
----
mkdir express-app
cd express-app
npx express-generator --view=pug
----

. Add a new OIDC App https://developer.okta.com/signup[on Okta]. Choose **Web** and use `http://localhost:3000/callback` for the login redirect; `http://localhost:3000` for the logout redirect.

. Install Schematics CLI:

  npm install -g @angular-devkit/schematics-cli

. Install and run OktaDev Schematics with your Okta value's for `$issuer`, `$clientId`, and `$clientSecret`:

  npm i @oktadev/schematics
  schematics @oktadev/schematics:add-auth --issuer=$issuer --clientId=$clientId --clientSecret=$clientSecret
+
CAUTION: An `.env` file will be generated with your client secret in it. Make sure to add `*.env` to `.gitignore` and don't check it into source control!

. Start your app and authenticate with Okta! 🚀

  npm start

== Learn More about Node.js and JavaScript

I hope you enjoyed this quick tour of how to add a login feature to a Node.js application. If you're looking to do more with Okta and Node.js, check out our https://github.com/okta/okta-sdk-nodejs[Node.js SDK]. It allows you to communicate with Okta APIs to manage your users and their identity.

You can find the source code for this example on GitHub https://github.com/oktadeveloper/okta-nodejs-login-example[@oktadeveloper/okta-nodejs-login-example].

If you liked this screencast, you might enjoy our other tutorials too.

- https://youtu.be/XJpYH7K7TGM[📺 Build a Secure Node.js App with SQL Server Step-by-Step]
- link:/blog/2020/04/22/build-secure-aws-lambda-nodejs-react[How to Build a Secure AWS Lambda API with Node.js and React]
- link:/blog/2019/12/04/whats-new-nodejs-2020[What's New for Node.js in 2020]
- link:/blog/2018/02/15/build-crud-app-vuejs-node[Build a Basic CRUD App with Vue.js and Node]
- link:/blog/2019/11/08/get-started-with-koa-for-node-apps[Get Started with Koa.js for Node Applications]

For more awesome tech talk, follow https://twitter.com/oktadev[@oktadev] on Twitter. We have a https://youtube.com/oktadev[fun YouTube channel] too! If you have any questions about Node.js, Okta, or anything related to this blog post, please ask in the comments below.
