---
layout: blog_post
title: "Get Started with Micronaut, JHipster, and OAuth"
author: matt-raible
by: advocate
communities: [java,javascript]
description: "This tutorial shows you how to create an app with Micronaut and JHipster and deploy it to Heroku."
tags: [java, micronaut, jhipster, oauth2, heroku]
tweets:
- ""
- ""
- ""
image:
type: conversion
---
:toc: macro
:page-liquid:

Micronaut is a new framework for developing APIs and microservices on the JVM. It's a direct competitor to Spring Boot from the folks that invented Grails. It's designed for fast startup times, which make it optimal for testing and running in serverless environments.

JHipster is a full-stack development platform for generating, developing, and deploying modern web applications and microservice architectures. JHipster has traditionally only had a Spring Boot backend implementation. However, other backend implementations have recently been added, including Micronaut!

JHipster has a concept called _blueprints_. Blueprints allow you to override default behavior in its application generator. Popular JHipster blueprints include https://github.com/jhipster/jhipster-vuejs[Vue.js] and https://github.com/jhipster/jhipster-kotlin[Kotlin].

Today, I'd like to show you how to use the new and shiny https://github.com/jhipster/generator-jhipster-micronaut[Micronaut Blueprint]. It supports Micronaut 2.0 and deploying to Heroku + adding Okta in one command. I figured it'd make for an excellent blog post!

// social image with words for width

== Build a Micronaut App with JHipster

JHipster has its own domain language called JDL (JHipster Domain Language). JDL can be used to describe an app, entities, relationships between entities, and even deployments. In this tutorial, I'll show you how to build a simple app that allows you to record space launches and add images to the event. It will look similar to NASA's https://www.nasa.gov/launchschedule/[Launches and Landings].

toc::[]

**Prerequisites:**

* https://adoptopenjdk.net/[Java 11]+
* https://nodejs.org/[Node 12]+
* https://docs.docker.com/get-docker/[Docker]
* An https://developer.okta.com/signup/[Okta Developer Account]

Install JHipster and the Micronaut blueprint using npm:

[source,shell]
----
npm i -g generator-jhipster generator-jhipster-micronaut # todo: add versions
----

== Design a Micronaut Data Model with JHipster's JDL

JHipster has defaults for all of its options. You can create a new app using the `jhipster` command, hold down the enter key when prompted with choices, and your app will be created with the defaults. https://www.jhipster.tech/jdl/[JDL] allows you to create an application definition where you only override the defaults. For example, you could create an app with OAuth 2.0 + OpenID Connect (OIDC) for authentication using the following JDL:

----
application {
  config {
    baseName rockets
    authenticationType oauth2
  }
}
----

Create a new directory called `spacefan`. Add an `app.jdl` file to it and populate it with the following code.

====
[source,json]
----
application { // <1>
  config {
    baseName space,
    applicationType monolith,
    authenticationType oauth2,
    packageName org.jhipster.space,
    prodDatabaseType postgresql,
    testFrameworks [protractor]
  }
  entities *
}

// <2>
entity Event {
	name String required
  date LocalDate required
  description TextBlob required
  photo ImageBlob required,
  type EventType required
}

entity Mission {
	name String required
  description String
}

enum EventType {
  Launch,
  Landing
}

// <3>
relationship OneToOne {
	Event{mission(name)} to Mission
}

// <4>
paginate Event with infinite-scroll
paginate Mission with pagination
----
. Application definition that overrides the name, authentication type, production database, and test frameworks.
. Entity definitions with validation rules.
. Relationships between entities.
. Pagination rules can be defined for each entity.
====

TIP: You can find additional JDL samples on GitHub in the https://github.com/jhipster/jdl-samples[jdl-samples repository].

== Generate a Micronaut App with Angular

Open a terminal and navigate to the `spacefan` directory you created. Run the following command to create an Angular app with a Micronaut backend.

[source,shell]
----
mhipster import-jdl app.jdl
----

This will create a plethora of files for your applications and run `npm install`. When it's finished, you'll need to start Keycloak.

[source,shell]
----
docker-compose -f src/main/docker/keycloak.yml up -d
----

TIP: If you're a Oh My Zsh fan, you can install the https://www.jhipster.tech/oh-my-zsh/[Oh My Zsh JHipster plugin] and just type `jhkeycloakup`.

Keycloak is the default OIDC engine that's used by JHipster and you can run it in a Docker container. In your project's `src/main/docker` folder, there's a Docker Compose file for Keynote, as well as default users, realms, and applications that are imported on startup.

=== What About React and Vue.js?

You might've noticed I didn't specify a client framework. I didn't need to because Angular is the default. If you wanted to use React instead, you simply need to add a `clientFramework react` line to the application definition in your JDL. For example:

----
application {
  config {
    baseName space,
    applicationType monolith,
    authenticationType oauth2,
    clientFramework react
    packageName org.jhipster.space,
    prodDatabaseType postgresql,
    testFrameworks [protractor]
  }
  entities *
}
----

NOTE: You can see all the default options in https://www.jhipster.tech/jdl/applications#available-application-configuration-options[JHipster's documentation].

If you want to use Vue.js instead of React, it's a little more complicated. First, you'll need to install the Vue.js blueprint:

[source,shell]
----
npm install -g generator-jhipster-vuejs
----

Then you'll need to import the JDL and specify both Micronaut and Vue.js as blueprints.

[source,shell]
----
jhipster import-jdl app.jdl --blueprints micronaut,vuejs
----

=== Confirm Authentication with Keycloak Works

With Keycloak up and running, you should be able to login. Start your app using Maven:

[source,source]
----
./mvn mn:run
----

When it finishes launching, go to `http://localhost:8080` in your favorite browser and click the **sign in** link.

// todo: screenshot

You'll be redirected to Keycloak to login. Use `admin/admin` to log in as an administrator.

// todo: keycloak screenshot

You can browse through the Administration section by clicking on the **Administration** menu.

// todo: screenshot of metrics

Go to **Entities** > **Events** to add new events and missions.

// todo: screenshot of entered data

NOTE: You might notice how both events and missions have existing data. This is from https://github.com/marak/Faker.js/[Faker.js] and https://www.liquibase.org/[Liquibase]. Liquibase is used to create your database tables and Faker.js is used to create fake data in development. If you want to turn off fake data, you can open `src/main/resources/config/application-dev.yml` and search for `faker`. Remove it from the list of active profiles in Liquibase.

// todo: code after removing liquibase

== Prepare Micronaut for Production

JHipster ships with profiles for development and production. In development, everything is designed to be fast for the developer. In production, everything should be fast for your users. When you build your app with the `prod` profile enabled, Micronaut is optimized with less logging and PostgreSQL. On the client side, scripts are optimized, CSS is minimized, and HTML is streamlined.

== Deploy Micronaut to Heroku

Since JHipster has production optimizations built-in, you're ready to deploy your app to Heroku!

To begin, you must install the https://cli.heroku.com/[Heroku CLI], and have a Heroku account created.

Then, run the following command:

[source,shell]
----
jhipster heroku
----

When prompted to add Okta, select Yes.

When deployment process finishes, open your favorite browser to the URL in your console, or run `heroku open`.

// todo: screenshot

You can also deploy your JHipster app as a Docker container! In https://developer.okta.com/blog/2020/06/17/angular-docker-spring-boot#heroku-spring-boot-docker[Angular + Docker with a Big Hug from Spring Boot], I showed you how to deploy Spring Boot to Heroku as a container. I also showed how you can deploy that same image to Knative on Google Cloud and Cloud Foundry. Once you have a JHipster + Micronaut image built, you can use those same instructions to deploy to those platforms.

In the next section, I'll show how to deploy your container to Heroku.

== Micronaut + Docker on Heroku

JHipster uses https://github.com/GoogleContainerTools/jib[Jib] to build Docker images for your application. Run the following command to build a Docker image.

[source,shell]
----
./mvnw package -Pprod verify jib:dockerBuild
----

You can test it out locally using Docker Compose.

[source,shell]
----
docker-compose -f src/main/docker/app.yml up
----

Once you've confirmed everything works, run the commands below to deploy your Micronaut app as a Docker image. Be sure to replace the `<...>` placeholders with your Heroku app name. If you don't know your app name, run `heroku apps`.

[source,shell]
----
docker tag todo:name-from-jhipster registry.heroku.com/<heroku-app>/web
docker push registry.heroku.com/<heroku-app>/web
heroku container:release web --remote docker
----

For example, I used:

[source,shell]
----
docker tag todo:name-from-jhipster registry.heroku.com/todo:real-app-name/web
docker push registry.heroku.com/todo:real-app-name/web
heroku container:release web --remote jib
----

You can watch the logs to see if your container started successfully.

[source,shell]
----
heroku logs --tail --remote docker
----

Since the Okta Add-on for Heroku configures everything for you, you should be able to open your app, click the **sign in** link, and authenticate!

[source,shell]
----
heroku open
----

// todo: remove if it's not easy to score an A

If you test your Dockerfied Angular + Micronaut app on https://securityheaders.com[securityheaders.com], you'll see it scores an **A+**!

// todo: screenshot

== Discover More About Micronaut and JHipster

I hope you enjoyed this whirlwind tour of Micronaut and JHipster. You can find the example created in this tutorial https://github.com/oktadeveloper/okta-jhipster-micronaut-example[on GitHub].

If you're interested in a performance comparison of Spring Boot and Micronaut in JHipster, see OCI's https://objectcomputing.com/news/2020/04/28/performance-comparison-spring-boot-micronaut[Practical Performance Comparison of Spring Boot, Micronaut 1.3, and Micronaut 2.0].

I hope you liked this hip tutorial! Here are some other ones that you might enjoy.

- https://developer.okta.com/blog/2020/01/09/java-rest-api-showdown[Java REST API Showdown: Which is the Best Framework on the Market?] https://youtu.be/pR_MBNL7cFI[📺]
* link:/blog/2019/05/23/java-microservices-spring-cloud-config[Java Microservices with Spring Cloud Config and JHipster] https://youtu.be/ez7HMO60kE8[📺]
* link:/blog/2019/04/04/java-11-java-12-jhipster-oidc[Better, Faster, Lighter Java with Java 12 and JHipster 6] https://youtu.be/Ktnvqoouulg[📺]
- https://developer.okta.com/blog/2020/04/27/mobile-development-ionic-react-native-jhipster[📺 Mobile Development with Ionic, React Native, and JHipster]

If you have any questions, please ask them in the comments below.

To be notified when we publish new blog posts, follow us on https://twitter.com/oktadev[Twitter] or https://www.linkedin.com/company/oktadev[LinkedIn]. We frequently publish videos to our https://youtube.com/c/oktadev[YouTube channel] too. Please https://youtube.com/c/oktadev?sub_confirmation=1[subscribe]!
