---
layout: blog_post
title: "Integrate Ionic and Spring Boot Securely"
author: matt-raible
by: advocate
communities: [mobile,java,javascript]
description: ""
tags: []
tweets:
- ""
image:
type: conversion
github:
---
:page-liquid:
:toc: macro
:experimental:

**Prerequisites:**

* https://adoptopenjdk.net/[Java 11+]
* https://nodejs.org[Node 14+]

toc::[]

== Build a Photo Gallery with JHipster

. Create a new directory to hold your frontend and backend projects: `take ionic-spring-boot`

. Clone an existing JHipster app into a `backend` directory:

  git clone https://github.com/oktadev/auth0-full-stack-java-example.git backend
  rm -rf backend/.git

. Start Keycloak:

  cd backend
  docker-compose -f src/main/docker/keycloak.yml up -d

. Start app using `./mvnw`, show project in IDE, and browse `http://localhost:8080`

. Add a few photos and show lightbox

== Generate an Ionic App

. Install Ionic CLI, Ionic for JHipster, and Yeoman

  npm i -g generator-jhipster-ionic @ionic/cli yo

. Create an Ionic app named `Flickr2`

  yo jhipster-ionic

. Rename `Flickr2` to `client`

  mv Flickr2 client
  cd client

. Launch app and log in after running `ionic serve`

. Generate entities using the JDL from the Spring Boot API

  yo jhipster-ionic:import-jdl ../backend/flickr2.jdl

. Hide metadata in `photo-update.html` with `<div *ngIf="!isNew">`

. Generate a native iOS project with the following commands:

  ionic build
  ionic capacitor add ios

. Add your custom scheme to `ios/App/App/Info.plist`:
+
[source,xml]
----
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLName</key>
    <string>com.getcapacitor.capacitor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>capacitor</string>
      <string>dev.localhost.ionic</string>
    </array>
  </dict>
</array>
----

. Modify the JHipster app's CORS settings (in `backend/src/main/resources/config/application-dev.yml`) to allow `capacitor://localhost` as an origin.

. Start your app with `npm start` and verify you can see photos

=== Run your App on iOS

. Run your app in Simulator.

  npx cap run ios

. You can also open your project in Xcode and run it from there.

  npx cap open ios

=== Run your App on Android

Change the custom scheme in `android/app/src/main/res/values/strings.xml` to use `dev.localhost.ionic`:

[source,xml]
----
<string name="custom_url_scheme">dev.localhost.ionic</string>
----

[source,shell]
----
npm install jetifier
npx jetify
npx cap sync android
----

Then, run your project using the Capacitor CLI:

[source,shell]
----
npx cap run android
----

You'll need to run a couple commands to allow the emulator to communicate with JHipster and Keycloak.

[source,shell]
----
adb reverse tcp:8080 tcp:8080
adb reverse tcp:9080 tcp:9080
----

If you see `java.io.IOException: Cleartext HTTP traffic to localhost not permitted` in your Android Studio console, enable clear text traffic in `android/app/src/main/AndroidManifest.xml`:

[source,xml]
----
<application
    ...
    android:usesCleartextTraffic="true">
----

== Use Auth0 for Identity

. Log in to your Auth0 account (or https://auth0.com/signup[sign up] if you don't have an account). You should have a unique domain like `dev-xxx.us.auth0.com`.

. Press the *Create Application* button in https://manage.auth0.com/#/applications[Applications section]. Use a name like `Ionic Rocks!`, select `Regular Web Applications`, and click *Create*.

. Switch to the *Settings* tab and configure your application settings:
+
- Allowed Callback URLs: `\http://localhost:8080/login/oauth2/code/oidc`
- Allowed Logout URLs: `\http://localhost:8080/`

. Scroll to the bottom and click *Save Changes*.

. In the https://manage.auth0.com/#/roles[roles] section, create new roles named `ROLE_ADMIN` and `ROLE_USER`.

. Create a new user account in the https://manage.auth0.com/#/users[users] section. Click on the *Role* tab to assign the roles you just created to the new account.
+
_Make sure your new user's email is verified before attempting to log in!_

. Next, head to *Auth Pipeline* > *Rules* > *Create*. Select the `Empty rule` template. Provide a meaningful name like `Group claims` and replace the Script content with the following.
+
[source,js]
----
function(user, context, callback) {
  user.preferred_username = user.email;
  const roles = (context.authorization || {}).roles;

  function prepareCustomClaimKey(claim) {
    return `https://www.jhipster.tech/${claim}`;
  }

  const rolesClaim = prepareCustomClaimKey('roles');

  if (context.idToken) {
    context.idToken[rolesClaim] = roles;
  }

  if (context.accessToken) {
    context.accessToken[rolesClaim] = roles;
  }

  callback(null, user, context);
}
----
+
This code is adding the user's roles to a custom claim (prefixed with `https://www.jhipster.tech/roles`). This claim is mapped to Spring Security authorities in `SecurityUtils.java`.

. Click *Save changes* to continue.

. Create a `backend/.auth0.env` file and populate it with your Auth0 settings.
+
[source,shell]
----
export SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://<your-auth0-domain>/
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=<your-client-id>
export SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=<your-client-secret>
export JHIPSTER_SECURITY_OAUTH2_AUDIENCE=https://<your-auth0-domain>/api/v2/
----
+
You can use the default `Auth0 Management API` audience value from the *Applications* > *API* > *API Audience* field. You can also define your own custom API and use the identifier as the API audience.

=== Create a Native OIDC App

. For Ionic, create a *Native* app and add the following Allowed Callback URLs:

  http://localhost:8100/callback,dev.localhost.ionic:/callback

. Set the Allowed Logout URLs to:

  http://localhost:8100/logout,dev.localhost.ionic:/logout

. Set the Allowed Origins (CORS):

  http://localhost:8100 # is capacitor://localhost needed?

. Update `ionic/src/app/auth/auth-config.service.ts` to use the generated client ID:

  environment.oidcConfig.server_host = this.authConfig.issuer;
  environment.oidcConfig.client_id = 'Dz7Oc9Zv9onjUBsdC55wReC4ifGMlA7G';

. Update `environment.ts` to specify your audience.
+
[source,ts]
----
export const environment = {
  ...
  oidcConfig: {
    ...
    audience: 'https://<your-auth0-domain>/api/v2/'
  },
  ...
};
----

. Restart your mobile apps and log in with Auth0!
+
----
npx cap run ios
----

== Doesn't work

- Ionic Android login
- Auth0 logout

